services:

  db-postgres:
    image: postgres
    restart: always
    ports:
     - "5435:5432"
    container_name: "db-postgresql"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass